---
title: "morphine_regression"
author: "nbergum"
date: "7/25/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(car)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(ggthemes)
library(lme4)
library(EnvStats)
library(nortest)
```

```{r}
regression <- read.csv("C:\\Users\\nikbe\\Documents\\Vigh Lab\\morphine_sex_differences\\morphine__sex_diff_transporters.csv", fileEncoding = 'UTF-8-BOM')
regression$conc_wt <- (regression$raw_conc/regression$tissue_weight)
str(regression)
```

```{r}
pgp_plot <- ggplot(regression, aes(pgp, conc_wt, col=tissue)) + geom_point() + geom_smooth(method = "lm", se = T) + xlim(0,7)
pgp_plot

ggsave("pgp_plot.svg", plot=pgp_plot, width=10, height =8)

bcrp_plot <- ggplot(regression, aes(bcrp, conc_wt, col=tissue)) + geom_point() + geom_smooth(method = "lm", se = T)+ xlim(0,7)
bcrp_plot

ggsave("bcrp_plot.svg", plot=bcrp_plot, width=10, height =8)
```

```{r}
regression_brain <- subset(regression, tissue == "brain")
regression_brain
shapiro.test(regression_brain$pgp)
shapiro.test(regression_brain$conc_wt)
shapiro.test(regression_brain$bcrp)
cor(regression_brain$pgp, regression_brain$conc_wt, method = "pearson")
cor.test(regression_brain$pgp, regression_brain$conc_wt, method = "pearson")
cor(regression_brain$bcrp, regression_brain$conc_wt, method = "pearson")
cor.test(regression_brain$bcrp, regression_brain$conc_wt, method = "pearson")
```
```{r}
regression_retina <- subset(regression, tissue == "retina")
shapiro.test(regression_retina$pgp)
shapiro.test(regression_retina$conc_wt)
cor(regression_retina$pgp, regression_retina$conc_wt, method = "pearson")
cor.test(regression_retina$pgp, regression_retina$conc_wt, method = "pearson")
```

```{r}
shapiro.test(regression_retina$bcrp)
cor(regression_retina$bcrp, regression_retina$conc_wt, method = "pearson")
cor.test(regression_retina$bcrp, regression_retina$conc_wt, method = "pearson")
```

```{r}
lm_ex <- lm(log(conc_wt) ~ log2(pgp)*tissue + log2(bcrp)*tissue, data = regression)
summary(lm_ex)
plot(lm_ex)
summary(lm_ex)$coefficient
```
