---
title: "qPCR Transporter Figures"
author: "C-T Berezin"
date: "7/21/2022"
output:
  pdf_document: default
---

```{r, message=FALSE, error=FALSE}
library(tidyverse)
library(ggthemes)
library(ggpubr)
library(emmeans)
library(lme4)
library(car)
library(lmerTest)
library(svglite)
```

### Bcrp & Mrp2 "baseline" expression (qPCR)

```{r}
#read in the data
getwd()
bm_data <- read.csv("../../data/qRT-PCR/Mrp-Bcrp-gene-study-subset-sal-ret-only.csv", fileEncoding = 'UTF-8-BOM')
bm_data <- bm_data %>% mutate(Sample = as.factor(Sample))

bm_data

#make the data so we can more easily plot both genes on the same graph
bm_data_long <- bm_data %>% pivot_longer(cols=c("Bcrp.RGE", "Mrp2.RGE"), names_to = "gene", values_to="rge")

bm_data_long <- bm_data_long %>% mutate(gene = fct_recode(as.factor(gene), Bcrp = "Bcrp.RGE", Mrp2 = "Mrp2.RGE"))

#get some summary statistics
bm_sumstats <- bm_data_long %>% group_by(gene) %>% summarise(n = n(),
                                                             mean = mean(rge),
                                                             sd = sd(rge),
                                                             se = sd/sqrt(n))

bm_sumstats

#plot
bm_plot <- ggplot() +
  stat_summary(fun = 'mean', geom="bar", width=0.75, data=bm_data_long, aes(x=gene, y=rge)) +
  #stat_summary(fun.data = mean_se, geom = "errorbar", width=.2) +
  geom_errorbar(width=0.2, data=bm_sumstats, aes(x=gene, ymin=mean-se, ymax=mean+se)) +
  geom_point(aes(x=gene, y=rge), data=bm_data_long) +
  geom_line(data=bm_data_long, aes(x=gene, y=rge, group=Sample)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme_bw(12) +
  labs(x="Gene", y="Relative Gene Expression")

bm_plot

#ggsave("../../figures/qRT-PCR/bcrp_mrp2_plot.png", plot=bm_plot, height=4, width=4)
#ggsave("../../figures/qRT-PCR/bcrp_mrp2_plot.svg", plot=bm_plot, height=4, width=4)

#checking assumptions of t-test
#normality
shapiro.test(bm_data$Bcrp.RGE)
shapiro.test(bm_data$Mrp2.RGE)
ggqqplot(bm_data, x = "Bcrp.RGE")
ggqqplot(bm_data, x = "Mrp2.RGE")
#no sig outliers in the difference between the groups
bm_data_stats <- bm_data %>% mutate(differences = Bcrp.RGE - Mrp2.RGE)
rstatix::identify_outliers(data=bm_data_stats, differences)

t.test(rge ~ gene, data=bm_data_long, paired=TRUE)

```
