---
title: "Transporter Colocalization Analysis (ImageJ Coloc2)"
author: "CT Berezin"
date: "2022-12-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(openxlsx)
library(coin)
library(viridis)
library(ggpubr)
library(svglite)
library(car)
```

M1 = occludin overlapping P-gp/Bcrp/Mrp2
M2 = P-gp/Bcrp/Mrp2 overlapping occludin

## Reading in the data

### P-gp

```{r}
#starting with the raw data
#pgp_filelist <- list.files(path="../data/IHC/coloc2_results_pgp/",
#                           pattern="*.txt", full.names = TRUE)
#pgp_cols <- c("sample", "m1", "m2", "r_pearson", "Pval", "r_rand", "sd_rand")
#pgp_coloc2 <- as.data.frame(matrix(,1,length(pgp_cols)))
#names(pgp_coloc2) <- pgp_cols

#for (i in pgp_filelist) {
#  test <- read_lines(i)
#  sample <- str_subset(test, "Working on") %>%
#    str_extract(., "(?<=:[:space:]).*")
#  r_pearson <- str_subset(test, "no threshold") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  m1 <- str_subset(test, "tM1") %>% str_extract(., "(?<=,[:space:]).*")
#  m2 <- str_subset(test, "tM2") %>% str_extract(., "(?<=,[:space:]).*")
#  Pval <- str_subset(test, "P-Value") %>% str_extract(., "(?<=,[:space:]).*")
#  r_rand <- str_subset(test, "Costes Shuffled Mean") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  sd_rand <- str_subset(test, "Costes Shuffled Std") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  res <- c(all_of(sample), all_of(m1), all_of(m2), all_of(r_pearson),
#           all_of(Pval), all_of(r_rand), all_of(sd_rand))
#  pgp_coloc2 <- rbind(pgp_coloc2, res)
#}

#pgp_coloc2 <- pgp_coloc2 %>% na.omit(pgp_coloc2) %>%
#  mutate(sex = as.factor(str_sub(sample, start=1L, end=1L)),
#        mouseID = as.factor(str_extract(sample, "(?<=-)[:digit:]+")),
       #prep = as.factor(str_extract(sample, "[:lower:]{2,}")),
#        prep = as.factor(str_extract(sample, "wm|section")),
#        image = str_extract(sample, "[:alpha:]{2,}.*"), .before=m1)

#pgp_coloc2 <- pgp_coloc2 %>% select(-sample) %>%
#  mutate(m1 = as.double(m1),
#        m2 = as.double(m2),
#        r_pearson = as.double(r_pearson),
#        Pval = as.double(Pval),
#        r_rand = as.double(r_rand),
#        sd_rand = as.double(sd_rand),
#        coloc = Pval>0.95)

#write.xlsx(pgp_coloc2, "../data/IHC/coloc2-pgp-totals.xlsx")

#starting from the processed excel sheet
pgp_coloc2 <- readxl::read_excel("../data/IHC/coloc2-pgp-totals.xlsx") %>% 
  mutate(coloc = as.logical(coloc),
         sex = as.factor(sex),
         mouseID = as.factor(mouseID),
         prep = as.factor(prep))

head(pgp_coloc2)
```

### Bcrp

```{r}
#starting with the raw data
#bcrp_filelist <- list.files(path="../data/IHC/coloc2_results_bcrp/",
#                            pattern=".*.txt", full.names = TRUE)
#bcrp_cols <- c("sample", "m1", "m2", "r_pearson", "Pval", "r_rand", "sd_rand")
#bcrp_coloc2 <- as.data.frame(matrix(,1,length(bcrp_cols)))
#names(bcrp_coloc2) <- bcrp_cols

#for (i in bcrp_filelist) {
#  test <- read_lines(i)
#  sample <- str_subset(test, "Working on") %>%
#    str_extract(., "(?<=:[:space:]).*")
#  r_pearson <- str_subset(test, "no threshold") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  m1 <- str_subset(test, "tM1") %>% str_extract(., "(?<=,[:space:]).*")
#  m2 <- str_subset(test, "tM2") %>% str_extract(., "(?<=,[:space:]).*")
#  Pval <- str_subset(test, "P-Value") %>% str_extract(., "(?<=,[:space:]).*")
#  r_rand <- str_subset(test, "Costes Shuffled Mean") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  sd_rand <- str_subset(test, "Costes Shuffled Std") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  print(sample)
#  res <- c(all_of(sample), all_of(m1), all_of(m2), all_of(r_pearson),
#           all_of(Pval), all_of(r_rand), all_of(sd_rand))
#  bcrp_coloc2 <- rbind(bcrp_coloc2, res)
#}

#bcrp_coloc2 <- bcrp_coloc2 %>% na.omit(bcrp_coloc2) %>%
#  mutate(sex = as.factor(str_sub(sample, start=1L, end=1L)),
#        mouseID = as.factor(str_extract(sample, "(?<=-)[:digit:]+")),
#        prep = as.factor(str_extract(sample, "[:lower:]{2,}")),
#        image = str_extract(sample, "[:alpha:]{2,}.*"), .before=m1)

#bcrp_coloc2 <- bcrp_coloc2 %>% select(-sample) %>%
#  mutate(m1 = as.double(m1),
#        m2 = as.double(m2),
#        r_pearson = as.double(r_pearson),
#        Pval = as.double(Pval),
#        r_rand = as.double(r_rand),
#        sd_rand = as.double(sd_rand),
#        coloc = Pval>0.95)

#write.xlsx(bcrp_coloc2, "../data/IHC/coloc2-bcrp-totals.xlsx")

#starting from processed excel file
bcrp_coloc2 <- readxl::read_excel("../data/IHC/coloc2-bcrp-totals.xlsx") %>% 
  mutate(coloc = as.logical(coloc),
         sex = as.factor(sex),
         mouseID = as.factor(mouseID),
         prep = as.factor(prep))

head(bcrp_coloc2)
```

### Mrp2

```{r}
#starting with raw data
#mrp2_filelist <- list.files(path="../data/IHC/coloc2_results_mrp2/",
#                            pattern="*.txt", full.names = TRUE)
#mrp2_cols <- c("sample", "m1", "m2", "r_pearson", "Pval", "r_rand", "sd_rand")
#mrp2_coloc2 <- as.data.frame(matrix(,1,length(mrp2_cols)))
#names(mrp2_coloc2) <- mrp2_cols

#for (i in mrp2_filelist) {
#  test <- read_lines(i)
#  sample <- str_subset(test, "Working on") %>%
#    str_extract(., "(?<=:[:space:]).*")
#  r_pearson <- str_subset(test, "no threshold") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  m1 <- str_subset(test, "tM1") %>% str_extract(., "(?<=,[:space:]).*")
#  m2 <- str_subset(test, "tM2") %>% str_extract(., "(?<=,[:space:]).*")
#  Pval <- str_subset(test, "P-Value") %>% str_extract(., "(?<=,[:space:]).*")
#  r_rand <- str_subset(test, "Costes Shuffled Mean") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  sd_rand <- str_subset(test, "Costes Shuffled Std") %>%
#    str_extract(., "(?<=,[:space:]).*")
#  res <- c(all_of(sample), all_of(m1), all_of(m2), all_of(r_pearson),
#           all_of(Pval), all_of(r_rand), all_of(sd_rand))
#  mrp2_coloc2 <- rbind(mrp2_coloc2, res)
#}

#mrp2_coloc2 <- mrp2_coloc2 %>% na.omit(mrp2_coloc2) %>%
#  mutate(sex = as.factor(str_sub(sample, start=1L, end=1L)),
#          mouseID = as.factor(str_extract(sample, "(?<=-)[:digit:]+")),
#          image = str_extract(sample, "s.*(?=_)"),
#          roi = str_extract(sample, "(?<=_).*"), .before=m1)

#mrp2_coloc2 <- mrp2_coloc2 %>% select(-sample) %>%
#  mutate(m1 = as.double(m1),
#        m2 = as.double(m2),
#        r_pearson = as.double(r_pearson),
#        Pval = as.double(Pval),
#        r_rand = as.double(r_rand),
#        sd_rand = as.double(sd_rand),
#        coloc = Pval>0.95)

#write.xlsx(mrp2_coloc2, "../data/IHC/coloc2-mrp2-totals.xlsx")

#starting with processed excel file
mrp2_coloc2 <- readxl::read_excel("../data/IHC/coloc2-mrp2-totals.xlsx") %>% 
  mutate(coloc = as.logical(coloc),
         sex = as.factor(sex),
         mouseID = as.factor(mouseID))


head(mrp2_coloc2)
```

## Generating summary statistics

### P-gp

```{r}
pgp_sumstats <- pgp_coloc2 %>% summarise(m1_mean = mean(m1),
                     m1_sd = sd(m1),
                     m2_mean = mean(m2),
                     m2_sd = sd(m2),
                     r_mean = mean(r_pearson),
                     r_sd = sd(r_pearson),
                     n_total = n(),
                     n_coloc = sum(coloc)
                     )
pgp_sumstats

bcrp_sumstats <- bcrp_coloc2 %>% summarise(m1_mean = mean(m1),
                     m1_sd = sd(m1),
                     m2_mean = mean(m2),
                     m2_sd = sd(m2),
                     r_mean = mean(r_pearson),
                     r_sd = sd(r_pearson),
                     n_total = n(),
                     n_coloc = sum(coloc),
                     mean_P = mean(Pval)
                     )
bcrp_sumstats

mrp2_sumstats <- mrp2_coloc2 %>% summarise(m1_mean = mean(m1),
                     m1_sd = sd(m1),
                     m2_mean = mean(m2),
                     m2_sd = sd(m2),
                     r_mean = mean(r_pearson),
                     r_sd = sd(r_pearson),
                     n_total = n(),
                     n_coloc = sum(coloc)
                     )
mrp2_sumstats

mrp2_sumstats_image <- mrp2_coloc2 %>% group_by(image,mouseID,sex,coloc) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc)
             )


pgp_sumstats_animals <- pgp_coloc2 %>% group_by(mouseID,sex,prep) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc)
             )
pgp_sumstats_animals

bcrp_sumstats_animals <- bcrp_coloc2 %>% group_by(mouseID,sex,prep) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc),
            mean_P = mean(Pval)
             )
bcrp_sumstats_animals

mrp2_sumstats_animals <- mrp2_coloc2 %>% group_by(mouseID,sex,coloc) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc)
             )
dropped <- mrp2_sumstats_animals %>% group_by(mouseID) %>%
  summarise(n = n(), coloc = coloc, sex=sex) %>%
  filter(n==1) %>% select(-n) %>%
  mutate(coloc = toString(as.integer(coloc))) %>% 
  mutate(coloc = str_replace(toString(coloc), pattern = "0", replacement = "1")) %>% 
  mutate(coloc = as.logical(as.integer(coloc)))

mrp2_sumstats_animals <- rbind(mrp2_sumstats_animals, dropped) %>% arrange(., mouseID)
mrp2_sumstats_animals <- mrp2_sumstats_animals %>% ungroup() %>% group_by(mouseID)

pgp_sumstats_sex <- pgp_coloc2 %>% group_by(sex) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc)
             )
pgp_sumstats_sex

bcrp_sumstats_sex <- bcrp_coloc2 %>% group_by(sex) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc)
             )
bcrp_sumstats_sex

mrp2_sumstats_sex <- mrp2_coloc2 %>% group_by(sex) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc)
             )
mrp2_sumstats_sex

pgp_sumstats_prep <- pgp_coloc2 %>% group_by(prep) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             mean_P = mean(Pval)
             )
pgp_sumstats_prep

mrp2_sumstats_coloc <- mrp2_coloc2 %>% group_by(coloc) %>% 
  summarise(m1_mean = mean(m1),
             m1_sd = sd(m1),
             m2_mean = mean(m2),
             m2_sd = sd(m2),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             mean_P = mean(Pval)
             )
mrp2_sumstats_coloc


```



## Plotting the data

  
```{r}
pgp_coloc2$coloc <- as.logical(pgp_coloc2$coloc)
pgp_coloc2$mouseID <- as.factor(pgp_coloc2$mouseID)

pgp_coloc2_long <- pgp_coloc2 %>% pivot_longer(cols = m1:m2, names_to = "m_stat_type", values_to = "m_stat_val")

pgp_coloc2_long <- pgp_coloc2_long %>% group_by(mouseID, m_stat_type, prep, sex) %>%
  summarise(m_mean = mean(m_stat_val),
             m_sd = sd(m_stat_val),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc))


#per animal
pgp_animal_r_plot <- pgp_sumstats_animals %>% 
  ggplot(aes(x=prep, y=r_mean)) +
  stat_summary(fun = 'mean', geom="bar", width=0.7) +
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) +  
  geom_jitter(color="black", width=0.1, aes(shape=sex)) +
  theme_bw(12) +
  guides(shape=guide_legend("Sex")) +
  ylim(-0.05,0.65) +
  ggtitle("P-gp")

pgp_animal_r_plot
ggsave("../figures/pgp_r_plot.png", plot=pgp_animal_r_plot, width=3, height=3)
ggsave("../figures/pgp_r_plot.svg", plot=pgp_animal_r_plot, width=3, height=3)

pgp_animal_m_plot <- ggplot(pgp_coloc2_long, aes(x=prep, y=m_mean)) +
  stat_summary(fun = 'mean', geom="bar", width=0.7) +
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) + 
  geom_jitter(color="black", width=0.1, aes(shape=sex)) +
  facet_wrap(~m_stat_type) +
  theme_bw(12) +
  guides(shape=guide_legend("Sex")) +
  ylim(-0.05,0.9) +
  ggtitle("P-gp")

pgp_animal_m_plot
ggsave("../figures/pgp_m_plot.png", plot=pgp_animal_m_plot, width=5, height=3)
ggsave("../figures/pgp_m_plot.svg", plot=pgp_animal_m_plot, width=5, height=3)
```

```{r}
bcrp_coloc2_long <- bcrp_coloc2 %>% pivot_longer(cols = m1:m2, names_to = "m_stat_type", values_to = "m_stat_val")

bcrp_coloc2_long <- bcrp_coloc2_long %>% group_by(mouseID, m_stat_type, sex) %>%
  summarise(m_mean = mean(m_stat_val),
             m_sd = sd(m_stat_val),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc))




#per animal
bcrp_animal_r_plot <- bcrp_sumstats_animals %>%
  ggplot(aes(x=sex, y=r_mean)) +
  stat_summary(fun = 'mean', geom="bar", width=0.7) +
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) +  
  geom_jitter(color="black", width=0.1, aes(shape=sex)) +
  theme_bw(12)  +
  guides(shape=guide_legend("Sex")) +
  ylim(-0.05,0.65) +
  ggtitle("Bcrp")

bcrp_animal_r_plot
ggsave("../figures/bcrp_r_plot.png", plot=bcrp_animal_r_plot, width=3, height=3)
ggsave("../figures/bcrp_r_plot.svg", plot=bcrp_animal_r_plot, width=3, height=3)

bcrp_animal_m_plot <- ggplot(bcrp_coloc2_long, aes(x=sex, y=m_mean)) +
  stat_summary(fun = 'mean', geom="bar", width=0.7) +
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) + 
  geom_jitter(color="black", width=0.1, aes(shape=sex)) +
  facet_wrap(~m_stat_type) +
  theme_bw(12)  +
  guides(shape=guide_legend("Sex")) +
  ylim(-0.05,0.9) +
  ggtitle("Bcrp")

bcrp_animal_m_plot
ggsave("../figures/bcrp_m_plot.png", plot=bcrp_animal_m_plot, width=5, height=3)
ggsave("../figures/bcrp_m_plot.svg", plot=bcrp_animal_m_plot, width=5, height=3)
```


```{r}
mrp2_coloc2$coloc <- as.logical(mrp2_coloc2$coloc)

mrp2_coloc2_long <- mrp2_coloc2 %>% pivot_longer(cols = m1:m2, names_to = "m_stat_type", values_to = "m_stat_val")

mrp2_coloc2_long <- mrp2_coloc2_long %>% group_by(mouseID, coloc, m_stat_type, sex) %>%
  summarise(m_stat_type = as.factor(m_stat_type),
            m_mean = mean(m_stat_val),
             m_sd = sd(m_stat_val),
             r_mean = mean(r_pearson),
             r_sd = sd(r_pearson),
             n_total = n(),
             n_coloc = sum(coloc))

mrp2_sumstats_animals_long <- mrp2_sumstats_animals %>% pivot_longer(cols = c(m1_mean,m2_mean), names_to = "m_stat_type", values_to = "m_stat_mean") %>% group_by(mouseID)

#per animal
mrp2_animal_r_plot <- mrp2_sumstats_animals %>% 
  ggplot(aes(x=coloc, y=r_mean)) +
  stat_summary(fun = 'mean', geom="bar", width=0.7) +
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) + 
  geom_jitter(color="black", width=0.1, aes(shape=sex)) +
  geom_line(aes(group=mouseID, color=mouseID)) +
  scale_color_viridis(discrete="TRUE") +
  theme_bw(12) +
  guides(shape=guide_legend("Sex"), color = "none") +
  ylim(-0.1,0.65) +
  ggtitle("Mrp2")

mrp2_animal_r_plot
ggsave("../figures/mrp2_r_plot.png", plot=mrp2_animal_r_plot, width=3, height=3)
ggsave("../figures/mrp2_r_plot.svg", plot=mrp2_animal_r_plot, width=3, height=3)

mrp2_animal_m_plot <- ggplot(mrp2_sumstats_animals_long, aes(x=coloc, y=m_stat_mean)) +
  stat_summary(fun = 'mean', geom="bar", width=0.7) +
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) + 
  geom_jitter(color="black", width=0.1, aes(shape=sex)) +
  geom_line(aes(group=mouseID, color=mouseID)) +
  facet_wrap(~m_stat_type) +
  scale_color_viridis(discrete="TRUE") +
  theme_bw(12) +
  guides(shape=guide_legend("Sex"), color = "none") +
  ylim(-0.05,0.9) +
  ggtitle("Mrp2")

mrp2_animal_m_plot
ggsave("../figures/mrp2_m_plot.png", plot=mrp2_animal_m_plot, width=5, height=3)
ggsave("../figures/mrp2_m_plot.svg", plot=mrp2_animal_m_plot, width=5, height=3)

```


## Statistical Tests

did sex affect pgp bcrp or mrp2_coloc2
did prep affect pgp parameters
were true and false coloc in mrp2 statistically different

```{r}
#normality
#pgp
car::qqPlot(pgp_sumstats_animals$r_mean)
shapiro.test(pgp_sumstats_animals$r_mean)

car::qqPlot(pgp_sumstats_animals$m1_mean)
shapiro.test(pgp_sumstats_animals$m1_mean)

car::qqPlot(pgp_sumstats_animals$m2_mean)
shapiro.test(pgp_sumstats_animals$m2_mean)


#hom variance
#pgp
leveneTest(pgp_sumstats_animals$r_mean ~ pgp_sumstats_animals$prep)
leveneTest(pgp_sumstats_animals$m1_mean ~ pgp_sumstats_animals$prep)
leveneTest(pgp_sumstats_animals$m2_mean ~ pgp_sumstats_animals$prep)

leveneTest(pgp_sumstats_animals$r_mean ~ pgp_sumstats_animals$sex)
leveneTest(pgp_sumstats_animals$m1_mean ~ pgp_sumstats_animals$sex)
leveneTest(pgp_sumstats_animals$m2_mean ~ pgp_sumstats_animals$sex)


t.test(pgp_sumstats_animals$r_mean ~ pgp_sumstats_animals$prep)
t.test(pgp_sumstats_animals$m1_mean ~ pgp_sumstats_animals$prep)
t.test(pgp_sumstats_animals$m2_mean ~ pgp_sumstats_animals$prep)

t.test(pgp_sumstats_animals$r_mean ~ pgp_sumstats_animals$sex)
t.test(pgp_sumstats_animals$m1_mean ~ pgp_sumstats_animals$sex)
t.test(pgp_sumstats_animals$m2_mean ~ pgp_sumstats_animals$sex)

pgp_r_lm <- lm(r_mean ~ prep + sex, data = pgp_sumstats_animals)
plot(pgp_r_lm)
anova(pgp_r_lm)
emmeans::emmeans(pgp_r_lm, pairwise ~ prep)$contrasts
emmeans::emmeans(pgp_r_lm, pairwise ~ sex)$contrasts

#pgp_r_lm <- lme4::lmer(r_mean ~ prep + sex + (1|mouseID), data = pgp_sumstats_animals)


coin::wilcox_test(pgp_sumstats_animals$r_mean ~ pgp_sumstats_animals$prep, conf.int=TRUE, distribution="exact")
coin::wilcox_test(pgp_sumstats_animals$m1_mean ~ pgp_sumstats_animals$prep, conf.int=TRUE, distribution="exact")
coin::wilcox_test(pgp_sumstats_animals$m2_mean ~ pgp_sumstats_animals$prep, conf.int=TRUE, distribution="exact")

coin::wilcox_test(pgp_sumstats_animals$r_mean ~ pgp_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
coin::wilcox_test(pgp_sumstats_animals$m1_mean ~ pgp_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
coin::wilcox_test(pgp_sumstats_animals$m2_mean ~ pgp_sumstats_animals$sex, conf.int=TRUE, distribution="exact")

```

```{r}
#normality
car::qqPlot(bcrp_sumstats_animals$r_mean)
shapiro.test(bcrp_sumstats_animals$r_mean)

car::qqPlot(bcrp_sumstats_animals$m1_mean)
shapiro.test(bcrp_sumstats_animals$m1_mean)

car::qqPlot(bcrp_sumstats_animals$m2_mean)
shapiro.test(bcrp_sumstats_animals$m2_mean)

#hom variance
leveneTest(bcrp_sumstats_animals$r_mean ~ bcrp_sumstats_animals$sex)
leveneTest(bcrp_sumstats_animals$m1_mean ~ bcrp_sumstats_animals$sex)
leveneTest(bcrp_sumstats_animals$m2_mean ~ bcrp_sumstats_animals$sex)


t.test(bcrp_sumstats_animals$r_mean ~ bcrp_sumstats_animals$sex)
t.test(bcrp_sumstats_animals$m1_mean ~ bcrp_sumstats_animals$sex)
t.test(bcrp_sumstats_animals$m2_mean ~ bcrp_sumstats_animals$sex)

coin::wilcox_test(bcrp_sumstats_animals$r_mean ~ bcrp_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
coin::wilcox_test(bcrp_sumstats_animals$m1_mean ~ bcrp_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
coin::wilcox_test(bcrp_sumstats_animals$m2_mean ~ bcrp_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
```


```{r}
mrp2_sumstats_animals_wide <- mrp2_sumstats_animals %>%
  pivot_wider(id_cols=!c(n_coloc, n_total), names_from = coloc,
              values_from = c(r_mean, r_sd, m1_mean, m1_sd, m2_mean, m2_sd))

colnames(mrp2_sumstats_animals_wide)
```
```{r}
#checking normality of differences for paired t test

mrp2_sumstats_animals_wide <- mrp2_sumstats_animals_wide %>%
  mutate(r_diffs = r_mean_TRUE - r_mean_FALSE,
         m1_diffs = m1_mean_TRUE - m1_mean_FALSE,
         m2_diffs = m2_mean_TRUE - m2_mean_FALSE)


car::qqPlot(mrp2_sumstats_animals_wide$r_diffs)
shapiro.test(mrp2_sumstats_animals_wide$r_diffs)
mrp2_sumstats_animals_wide %>% rstatix::identify_outliers(r_diffs)

car::qqPlot(mrp2_sumstats_animals_wide$m1_diffs)
shapiro.test(mrp2_sumstats_animals_wide$m1_diffs)
mrp2_sumstats_animals_wide %>% rstatix::identify_outliers(m1_diffs)

car::qqPlot(mrp2_sumstats_animals_wide$m2_diffs)
shapiro.test(mrp2_sumstats_animals_wide$m2_diffs)
mrp2_sumstats_animals_wide %>% rstatix::identify_outliers(m2_diffs)


mrp2_sumstats_animals$r_mean <- replace_na(mrp2_sumstats_animals$r_mean, 0)
mrp2_sumstats_animals$m1_mean <- replace_na(mrp2_sumstats_animals$m1_mean, 0)
mrp2_sumstats_animals$m2_mean <- replace_na(mrp2_sumstats_animals$m2_mean, 0)

t.test(mrp2_sumstats_animals$r_mean ~ mrp2_sumstats_animals$coloc, paired = TRUE)
t.test(mrp2_sumstats_animals$m1_mean ~ mrp2_sumstats_animals$coloc, paired = TRUE)
t.test(mrp2_sumstats_animals$m2_mean ~ mrp2_sumstats_animals$coloc, paired = TRUE)


mrp2_sumstats_animals$coloc <- as.factor(mrp2_sumstats_animals$coloc)

coin::wilcoxsign_test(r_mean ~ coloc | mouseID, data=mrp2_sumstats_animals, conf.int=TRUE, distribution="exact")
coin::wilcoxsign_test(m1_mean ~ coloc | mouseID, data=mrp2_sumstats_animals, conf.int=TRUE, distribution="exact")
coin::wilcoxsign_test(m2_mean ~ coloc | mouseID, data=mrp2_sumstats_animals, conf.int=TRUE, distribution="exact")


mrp2_pos_sumstats_animals <- mrp2_sumstats_animals %>% filter(coloc== TRUE)

coin::wilcox_test(mrp2_pos_sumstats_animals$r_mean ~ mrp2_pos_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
t.test(mrp2_sumstats_animals_wide$r_mean_TRUE ~ mrp2_sumstats_animals_wide$sex)
coin::wilcox_test(mrp2_pos_sumstats_animals$m1_mean ~ mrp2_pos_sumstats_animals$sex, conf.int=TRUE, distribution="exact")
coin::wilcox_test(mrp2_pos_sumstats_animals$m2_mean ~ mrp2_pos_sumstats_animals$sex, conf.int=TRUE, distribution="exact")



#mrp2_sumstats_animals_long
#mrp2_sumstats_animals_wide

#mrp2_coloc2_long <- mrp2_coloc2 %>% pivot_longer(cols = m1:m2, names_to = "m_stat_type", values_to = "m_stat_val")

#mrp2_coloc2_long <- mrp2_coloc2_long %>% group_by(mouseID, coloc, m_stat_type, sex) %>%
#  summarise(m_stat_type = as.factor(m_stat_type),
#            m_mean = mean(m_stat_val),
#             m_sd = sd(m_stat_val),
#             r_mean = mean(r_pearson),
#             r_sd = sd(r_pearson),
#             n_total = n(),
#             n_coloc = sum(coloc))

#mrp2_sumstats_animals_long <- mrp2_sumstats_animals %>% pivot_longer(cols = c(m1_mean,m2_mean), names_to = "m_stat_type", values_to = "m_stat_mean") %>% group_by(mouseID)
```

```{r}
intersect(pgp_sumstats_animals$mouseID,bcrp_sumstats_animals$mouseID)
intersect(pgp_sumstats_animals$mouseID,mrp2_sumstats_animals$mouseID)
intersect(bcrp_sumstats_animals$mouseID,mrp2_sumstats_animals$mouseID)
intersect(intersect(pgp_sumstats_animals$mouseID,bcrp_sumstats_animals$mouseID),mrp2_sumstats_animals$mouseID)
```